const topData = {
    company: [
      "Company",
      "About us",
      "Team",
      "Careers",
      "Swiggy Blog",
      "Bug Bounty",
      "Swiggy Super",
      "Swiggy Corporate",
      "Swiggy Instamart",
    ],
    contact: ["Contact", "Help & Support", "Partner with us", "Ride with us"],
    legal: [
      "Legal",
      "Terms & Conditions",
      "Refund & Cancellation",
      "Privacy Policy",
      "Cookie Policy",
      "Offer Terms",
      "Phishing & Fraud",
    ],
  };
  
  const cityName = {
    col1: [
      "Abohar",
      "Adilabad",
      "Adityapur",
      "Adoni",
      "Agartala",
      "Agra",
      "Ahmedabad",
      "Ahmednagar",
      "Ajmer",
      "Akola",
      "Alappuzha",
      "Aligarh",
      "Allahabad",
      "Alwar",
      "Ambala",
      "Ambikapur",
      "Ambur",
      "Amravati",
      "Amreli",
      "Amritsar",
    ],
    col2: [
      "Anand",
      "Anantapur",
      "Ankleshwar",
      "Arrah",
      "Asansol",
      "Ashoknagar",
      "Aurangabad",
      "Aurangabad_bihar",
      "Azamgarh",
      "Baddi",
      "Bagalkot",
      "Bagdogra",
      "Bahadurgarh",
      "Bahraich",
      "Bajpe",
      "Balaghat",
      "Ballari",
      "Balrampur",
      "Balurghat",
      "Bangalore",
    ],
    col3: [
      "Bolpur",
      "Bongaigaon",
      "Bongaon",
      "Botad",
      "Budaun",
      "Budhwal",
      "Bulandshahr",
      "Buldana",
      "Bundi",
      "Burhanpur",
      "Buxar",
      "Central-Goa",
      "Chalakkudy",
      "Chalisgaon",
      "Chandigarh",
      "Chandrapur",
      "Changanasherry",
      "Charkhi-Dadri",
      "Chengannur",
      "Chennai",
    ],
    col4: [
      "Bardhaman",
      "Bardoli",
      "Bareilly",
      "Barnala",
      "Barshi",
      "Basirhat",
      "Basti",
      "Batala",
      "Bathinda",
      "Beawar",
      "Beed",
      "Begusarai",
      "Belgaum",
      "Berhampore",
      "Berhampur",
      "Bettiah",
      "Betul",
      "Bhadrachalam",
      "Bhadravati",
      "Bhagalpur",
    ],
  };
  export { topData ,cityName};
  